GET http://localhost:3001/api/v1/welcome
Content-Type: application/json

### ĐĂNG KÝ
POST http://localhost:3001/api/v1/QuanLyNguoiDung/DangKy
Content-Type: application/json

{
  "taiKhoan": "vulebaolong",
  "matKhau": "123456",
  "email": "vulebaolong@gmail.com",
  "soDt": "0836789578",
  "hoTen": "Vũ Lê Bảo long"
}

### ĐĂNG NHẬP
POST http://localhost:3001/api/v1/QuanLyNguoiDung/DangNhap
Content-Type: application/json

{
  "taiKhoan": "vulebaolong",
  "matKhau": "123456"
}